//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorCode.
const (
	ErrorCodeClientOutdated     ErrorCode = "client_outdated"
	ErrorCodeDailyQuotaExceeded ErrorCode = "daily_quota_exceeded"
	ErrorCodeDataUnavailable    ErrorCode = "data_unavailable"
	ErrorCodeInternal           ErrorCode = "internal"
	ErrorCodeInvalidRegion      ErrorCode = "invalid_region"
	ErrorCodeInvalidRequest     ErrorCode = "invalid_request"
	ErrorCodeRateLimited        ErrorCode = "rate_limited"
	ErrorCodeRegionTooLarge     ErrorCode = "region_too_large"
	ErrorCodeRegionUnsupported  ErrorCode = "region_unsupported"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeClientOutdated:
		return true
	case ErrorCodeDailyQuotaExceeded:
		return true
	case ErrorCodeDataUnavailable:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidRegion:
		return true
	case ErrorCodeInvalidRequest:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeRegionTooLarge:
		return true
	case ErrorCodeRegionUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for PackageFileName.
const (
	BasemapPmtiles  PackageFileName = "basemap.pmtiles"
	ContoursPmtiles PackageFileName = "contours.pmtiles"
	DemPmtiles      PackageFileName = "dem.pmtiles"
)

// Valid indicates whether the value is a known member of the PackageFileName enum.
func (e PackageFileName) Valid() bool {
	switch e {
	case BasemapPmtiles:
		return true
	case ContoursPmtiles:
		return true
	case DemPmtiles:
		return true
	default:
		return false
	}
}

// Defines values for VersionApi.
const (
	V1 VersionApi = "v1"
)

// Valid indicates whether the value is a known member of the VersionApi enum.
func (e VersionApi) Valid() bool {
	switch e {
	case V1:
		return true
	default:
		return false
	}
}

// Defines values for GetTiandituTileParamsLayer.
const (
	Cia GetTiandituTileParamsLayer = "cia"
	Cva GetTiandituTileParamsLayer = "cva"
	Img GetTiandituTileParamsLayer = "img"
	Vec GetTiandituTileParamsLayer = "vec"
)

// Valid indicates whether the value is a known member of the GetTiandituTileParamsLayer enum.
func (e GetTiandituTileParamsLayer) Valid() bool {
	switch e {
	case Cia:
		return true
	case Cva:
		return true
	case Img:
		return true
	case Vec:
		return true
	default:
		return false
	}
}

// DataVersion defines model for DataVersion.
type DataVersion struct {
	Version string `json:"version"`
}

// Error defines model for Error.
type Error struct {
	Error ErrorCode `json:"error"`

	// MaxAreaKm2 set when error is region_too_large
	MaxAreaKm2 *int `json:"maxAreaKm2,omitempty"`

	// MinClientVersion set when error is client_outdated
	MinClientVersion *int `json:"minClientVersion,omitempty"`

	// QuotaBytes set when error is daily_quota_exceeded
	QuotaBytes *int64 `json:"quotaBytes,omitempty"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	// Postgis postgis_lib_version()
	Postgis string       `json:"postgis"`
	Status  HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// HealthDown defines model for HealthDown.
type HealthDown struct {
	Status string `json:"status"`
}

// Package defines model for Package.
type Package struct {
	Bytes   int64         `json:"bytes"`
	Files   []PackageFile `json:"files"`
	Version string        `json:"version"`
}

// PackageFile defines model for PackageFile.
type PackageFile struct {
	Bytes int64           `json:"bytes"`
	Name  PackageFileName `json:"name"`
	Url   string          `json:"url"`
}

// PackageFileName defines model for PackageFile.Name.
type PackageFileName string

// PackageRequest Exactly one of bbox or track.
type PackageRequest struct {
	// Bbox [west, south, east, north], WGS-84
	Bbox  *[]float64   `json:"bbox,omitempty"`
	Track *[][]float64 `json:"track,omitempty"`
}

// Version defines model for Version.
type Version struct {
	Api              VersionApi `json:"api"`
	MinClientVersion int        `json:"minClientVersion"`
}

// VersionApi defines model for Version.Api.
type VersionApi string

// ClientVersion defines model for ClientVersion.
type ClientVersion = int

// DeviceId defines model for DeviceId.
type DeviceId = string

// ClientOutdated defines model for ClientOutdated.
type ClientOutdated = Error

// DataUnavailable defines model for DataUnavailable.
type DataUnavailable = Error

// Internal defines model for Internal.
type Internal = Error

// RateLimited defines model for RateLimited.
type RateLimited = Error

// GetHealthParams defines parameters for GetHealth.
type GetHealthParams struct {
	XDeviceId      *DeviceId      `json:"X-Device-Id,omitempty"`
	XClientVersion *ClientVersion `json:"X-Client-Version,omitempty"`
}

// PostOfflinePackagesParams defines parameters for PostOfflinePackages.
type PostOfflinePackagesParams struct {
	XDeviceId      *DeviceId      `json:"X-Device-Id,omitempty"`
	XClientVersion *ClientVersion `json:"X-Client-Version,omitempty"`
}

// GetOfflineVersionParams defines parameters for GetOfflineVersion.
type GetOfflineVersionParams struct {
	XDeviceId      *DeviceId      `json:"X-Device-Id,omitempty"`
	XClientVersion *ClientVersion `json:"X-Client-Version,omitempty"`
}

// GetTiandituTileParams defines parameters for GetTiandituTile.
type GetTiandituTileParams struct {
	XDeviceId      *DeviceId      `json:"X-Device-Id,omitempty"`
	XClientVersion *ClientVersion `json:"X-Client-Version,omitempty"`
}

// GetTiandituTileParamsLayer defines parameters for GetTiandituTile.
type GetTiandituTileParamsLayer string

// GetVersionParams defines parameters for GetVersion.
type GetVersionParams struct {
	XDeviceId      *DeviceId      `json:"X-Device-Id,omitempty"`
	XClientVersion *ClientVersion `json:"X-Client-Version,omitempty"`
}

// PostOfflinePackagesJSONRequestBody defines body for PostOfflinePackages for application/json ContentType.
type PostOfflinePackagesJSONRequestBody = PackageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness plus database/PostGIS reachability
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams)
	// PostOfflinePackages Clip an offline package (spec §2.3) for a viewport or along a track
	// (POST /offline/packages)
	PostOfflinePackages(w http.ResponseWriter, r *http.Request, params PostOfflinePackagesParams)
	// GetOfflineVersion Version of the offline map data; packages downloaded under another version show "可更新"
	// (GET /offline/version)
	GetOfflineVersion(w http.ResponseWriter, r *http.Request, params GetOfflineVersionParams)
	// GetTiandituTile A 天地图 tile through the server, so the key never ships in the app (spec §2.2)
	// (GET /tiles/tianditu/{layer}/{z}/{x}/{y})
	GetTiandituTile(w http.ResponseWriter, r *http.Request, layer GetTiandituTileParamsLayer, z int, x int, y int, params GetTiandituTileParams)
	// GetVersion API version and the oldest client versionCode still served
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request, params GetVersionParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHealthParams

	headers := r.Header

	// ------------- Optional header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Device-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Device-Id", Err: err})
			return
		}

		params.XDeviceId = &XDeviceId

	}

	// ------------- Optional header parameter "X-Client-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Version")]; found {
		var XClientVersion ClientVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Version", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Version", valueList[0], &XClientVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Version", Err: err})
			return
		}

		params.XClientVersion = &XClientVersion

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostOfflinePackages operation middleware
func (siw *ServerInterfaceWrapper) PostOfflinePackages(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostOfflinePackagesParams

	headers := r.Header

	// ------------- Optional header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Device-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Device-Id", Err: err})
			return
		}

		params.XDeviceId = &XDeviceId

	}

	// ------------- Optional header parameter "X-Client-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Version")]; found {
		var XClientVersion ClientVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Version", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Version", valueList[0], &XClientVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Version", Err: err})
			return
		}

		params.XClientVersion = &XClientVersion

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostOfflinePackages(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOfflineVersion operation middleware
func (siw *ServerInterfaceWrapper) GetOfflineVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOfflineVersionParams

	headers := r.Header

	// ------------- Optional header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Device-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Device-Id", Err: err})
			return
		}

		params.XDeviceId = &XDeviceId

	}

	// ------------- Optional header parameter "X-Client-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Version")]; found {
		var XClientVersion ClientVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Version", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Version", valueList[0], &XClientVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Version", Err: err})
			return
		}

		params.XClientVersion = &XClientVersion

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOfflineVersion(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTiandituTile operation middleware
func (siw *ServerInterfaceWrapper) GetTiandituTile(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "layer" -------------
	var layer GetTiandituTileParamsLayer

	err = runtime.BindStyledParameterWithOptions("simple", "layer", r.PathValue("layer"), &layer, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "layer", Err: err})
		return
	}

	// ------------- Path parameter "z" -------------
	var z int

	err = runtime.BindStyledParameterWithOptions("simple", "z", r.PathValue("z"), &z, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "z", Err: err})
		return
	}

	// ------------- Path parameter "x" -------------
	var x int

	err = runtime.BindStyledParameterWithOptions("simple", "x", r.PathValue("x"), &x, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x", Err: err})
		return
	}

	// ------------- Path parameter "y" -------------
	var y int

	err = runtime.BindStyledParameterWithOptions("simple", "y", r.PathValue("y"), &y, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "y", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTiandituTileParams

	headers := r.Header

	// ------------- Optional header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Device-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Device-Id", Err: err})
			return
		}

		params.XDeviceId = &XDeviceId

	}

	// ------------- Optional header parameter "X-Client-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Version")]; found {
		var XClientVersion ClientVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Version", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Version", valueList[0], &XClientVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Version", Err: err})
			return
		}

		params.XClientVersion = &XClientVersion

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTiandituTile(w, r, layer, z, x, y, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVersionParams

	headers := r.Header

	// ------------- Optional header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Device-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Device-Id", Err: err})
			return
		}

		params.XDeviceId = &XDeviceId

	}

	// ------------- Optional header parameter "X-Client-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Version")]; found {
		var XClientVersion ClientVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Client-Version", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Version", valueList[0], &XClientVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Client-Version", Err: err})
			return
		}

		params.XClientVersion = &XClientVersion

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/version", wrapper.GetVersion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/offline/version", wrapper.GetOfflineVersion)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/offline/packages", wrapper.PostOfflinePackages)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tiles/tianditu/{layer}/{z}/{x}/{y}", wrapper.GetTiandituTile)

	return m
}

type ClientOutdatedJSONResponse Error

type DataUnavailableJSONResponse Error

type InternalJSONResponse Error

type RateLimitedJSONResponse Error

type GetHealthRequestObject struct {
	Params GetHealthParams
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth429JSONResponse struct{ RateLimitedJSONResponse }

func (response GetHealth429JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse HealthDown

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PostOfflinePackagesRequestObject struct {
	Params PostOfflinePackagesParams
	Body   *PostOfflinePackagesJSONRequestBody
}

type PostOfflinePackagesResponseObject interface {
	VisitPostOfflinePackagesResponse(w http.ResponseWriter) error
}

type PostOfflinePackages200JSONResponse Package

func (response PostOfflinePackages200JSONResponse) VisitPostOfflinePackagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PostOfflinePackages400JSONResponse Error

func (response PostOfflinePackages400JSONResponse) VisitPostOfflinePackagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PostOfflinePackages426JSONResponse struct{ ClientOutdatedJSONResponse }

func (response PostOfflinePackages426JSONResponse) VisitPostOfflinePackagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(426)
	_, err := buf.WriteTo(w)
	return err
}

type PostOfflinePackages429JSONResponse Error

func (response PostOfflinePackages429JSONResponse) VisitPostOfflinePackagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type PostOfflinePackages500JSONResponse struct{ InternalJSONResponse }

func (response PostOfflinePackages500JSONResponse) VisitPostOfflinePackagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type PostOfflinePackages503JSONResponse struct{ DataUnavailableJSONResponse }

func (response PostOfflinePackages503JSONResponse) VisitPostOfflinePackagesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetOfflineVersionRequestObject struct {
	Params GetOfflineVersionParams
}

type GetOfflineVersionResponseObject interface {
	VisitGetOfflineVersionResponse(w http.ResponseWriter) error
}

type GetOfflineVersion200JSONResponse DataVersion

func (response GetOfflineVersion200JSONResponse) VisitGetOfflineVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOfflineVersion426JSONResponse struct{ ClientOutdatedJSONResponse }

func (response GetOfflineVersion426JSONResponse) VisitGetOfflineVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(426)
	_, err := buf.WriteTo(w)
	return err
}

type GetOfflineVersion429JSONResponse struct{ RateLimitedJSONResponse }

func (response GetOfflineVersion429JSONResponse) VisitGetOfflineVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetOfflineVersion500JSONResponse struct{ InternalJSONResponse }

func (response GetOfflineVersion500JSONResponse) VisitGetOfflineVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetOfflineVersion503JSONResponse struct{ DataUnavailableJSONResponse }

func (response GetOfflineVersion503JSONResponse) VisitGetOfflineVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetTiandituTileRequestObject struct {
	Layer  GetTiandituTileParamsLayer `json:"layer"`
	Z      int                        `json:"z"`
	X      int                        `json:"x"`
	Y      int                        `json:"y"`
	Params GetTiandituTileParams
}

type GetTiandituTileResponseObject interface {
	VisitGetTiandituTileResponse(w http.ResponseWriter) error
}

type GetTiandituTile200ResponseHeaders struct {
	CacheControl *string
}

type GetTiandituTile200ImageResponse struct {
	Body          io.Reader
	Headers       GetTiandituTile200ResponseHeaders
	ContentType   string
	ContentLength int64
}

func (response GetTiandituTile200ImageResponse) VisitGetTiandituTileResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetTiandituTile400JSONResponse Error

func (response GetTiandituTile400JSONResponse) VisitGetTiandituTileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTiandituTile426JSONResponse struct{ ClientOutdatedJSONResponse }

func (response GetTiandituTile426JSONResponse) VisitGetTiandituTileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(426)
	_, err := buf.WriteTo(w)
	return err
}

type GetTiandituTile429JSONResponse struct{ RateLimitedJSONResponse }

func (response GetTiandituTile429JSONResponse) VisitGetTiandituTileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetTiandituTile500JSONResponse struct{ InternalJSONResponse }

func (response GetTiandituTile500JSONResponse) VisitGetTiandituTileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTiandituTile503JSONResponse struct{ DataUnavailableJSONResponse }

func (response GetTiandituTile503JSONResponse) VisitGetTiandituTileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersionRequestObject struct {
	Params GetVersionParams
}

type GetVersionResponseObject interface {
	VisitGetVersionResponse(w http.ResponseWriter) error
}

type GetVersion200JSONResponse Version

func (response GetVersion200JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVersion429JSONResponse struct{ RateLimitedJSONResponse }

func (response GetVersion429JSONResponse) VisitGetVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Liveness plus database/PostGIS reachability
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// PostOfflinePackages Clip an offline package (spec §2.3) for a viewport or along a track
	// (POST /offline/packages)
	PostOfflinePackages(ctx context.Context, request PostOfflinePackagesRequestObject) (PostOfflinePackagesResponseObject, error)
	// GetOfflineVersion Version of the offline map data; packages downloaded under another version show "可更新"
	// (GET /offline/version)
	GetOfflineVersion(ctx context.Context, request GetOfflineVersionRequestObject) (GetOfflineVersionResponseObject, error)
	// GetTiandituTile A 天地图 tile through the server, so the key never ships in the app (spec §2.2)
	// (GET /tiles/tianditu/{layer}/{z}/{x}/{y})
	GetTiandituTile(ctx context.Context, request GetTiandituTileRequestObject) (GetTiandituTileResponseObject, error)
	// GetVersion API version and the oldest client versionCode still served
	// (GET /version)
	GetVersion(ctx context.Context, request GetVersionRequestObject) (GetVersionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request, params GetHealthParams) {
	var request GetHealthRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostOfflinePackages operation middleware
func (sh *strictHandler) PostOfflinePackages(w http.ResponseWriter, r *http.Request, params PostOfflinePackagesParams) {
	var request PostOfflinePackagesRequestObject

	request.Params = params

	var body PostOfflinePackagesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostOfflinePackages(ctx, request.(PostOfflinePackagesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostOfflinePackages")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostOfflinePackagesResponseObject); ok {
		if err := validResponse.VisitPostOfflinePackagesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOfflineVersion operation middleware
func (sh *strictHandler) GetOfflineVersion(w http.ResponseWriter, r *http.Request, params GetOfflineVersionParams) {
	var request GetOfflineVersionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOfflineVersion(ctx, request.(GetOfflineVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOfflineVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOfflineVersionResponseObject); ok {
		if err := validResponse.VisitGetOfflineVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTiandituTile operation middleware
func (sh *strictHandler) GetTiandituTile(w http.ResponseWriter, r *http.Request, layer GetTiandituTileParamsLayer, z int, x int, y int, params GetTiandituTileParams) {
	var request GetTiandituTileRequestObject

	request.Layer = layer
	request.Z = z
	request.X = x
	request.Y = y
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTiandituTile(ctx, request.(GetTiandituTileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTiandituTile")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTiandituTileResponseObject); ok {
		if err := validResponse.VisitGetTiandituTileResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVersion operation middleware
func (sh *strictHandler) GetVersion(w http.ResponseWriter, r *http.Request, params GetVersionParams) {
	var request GetVersionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVersion(ctx, request.(GetVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVersionResponseObject); ok {
		if err := validResponse.VisitGetVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
