#!/usr/bin/env bash
#
# 部署服务端：构建并推送镜像到 registry.starsdom.com:9443，再让 root@192.168.50.51 拉取并重启。
# 用法：scripts/deploy.sh [版本号]   （不填用 git 短哈希；同时打 latest）
# 首次部署会上传 deploy/.env 和 deploy/certs，并登录服务器上的镜像仓库；之后这些步骤自动跳过。
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, on Linux, macOS or WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

REGISTRY=registry.starsdom.com:9443
IMAGE=$REGISTRY/zibyn/stars-outdoor-server
HOST=root@192.168.50.51
DIR=/opt/outdoor
REPO=$(cd "$(dirname "$0")/.." && pwd)
VERSION=${1:-$(git -C "$REPO" rev-parse --short HEAD)}
remote() { ssh -o BatchMode=yes "$HOST" "$@"; }

banner "部署服务端 $VERSION → $HOST:$DIR"

stage "本机登录镜像仓库"
if grep -q "\"$REGISTRY\"" ~/.docker/config.json 2>/dev/null; then
  say "已登录 $REGISTRY，跳过。"
else
  say "推送镜像需要 $REGISTRY 的账号。"
  ask REGISTRY_USER "用户名："
  ask_secret REGISTRY_PASSWORD "密码（或访问令牌）："
  printf '%s' "$REGISTRY_PASSWORD" | docker login "$REGISTRY" -u "$REGISTRY_USER" --password-stdin
fi

stage "构建并推送镜像"
[[ -z "$(git -C "$REPO" status --porcelain server)" ]] || warn "server/ 有未提交的改动，会一起打进镜像"
say "镜像：$IMAGE:$VERSION 和 :latest"
confirm "构建并推送？" || { warn "已取消"; exit 1; }
docker build -t "$IMAGE:$VERSION" -t "$IMAGE:latest" "$REPO/server"
docker push "$IMAGE:$VERSION"
docker push "$IMAGE:latest"

stage "免密 SSH 到 $HOST"
if remote true 2>/dev/null; then
  say "免密登录正常，跳过。"
else
  say "需要把本机公钥加到服务器，接下来会问一次 root 密码。"
  [[ -f ~/.ssh/id_ed25519.pub || -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519
  ssh-copy-id "$HOST"
  remote true || { warn "仍无法免密登录"; exit 1; }
fi
remote "docker compose version" >/dev/null || { warn "服务器上没有 docker compose，先装好 Docker 再重跑"; exit 1; }

stage "准备服务器 $DIR"
# The server has no ../server to build from: it only pulls.
sed '/^    build: \.\.\/server$/d' "$REPO/deploy/compose.yaml" | remote "mkdir -p $DIR && cat > $DIR/compose.yaml"
say "✓ 已同步 compose.yaml"
if remote "test -f $DIR/.env"; then
  say "服务器已有 .env，跳过（要改配置请直接在服务器上改 $DIR/.env）。"
else
  warn "首次部署：会把本机 deploy/.env（含数据库密码和第三方密钥）复制到服务器。"
  note "S3_ENDPOINT 必须是手机能访问的地址；服务器上会新建一个空数据库。"
  confirm "复制？" || { warn "已取消"; exit 1; }
  scp -q "$REPO/deploy/.env" "$HOST:$DIR/.env"
  remote "chmod 600 $DIR/.env"
  say "✓ 已复制 .env"
fi
# certs/ every time (a few bytes), so a changed key reaches the server. Read through Docker (root): the key is
# owned by 65532 here too, for the local API. tar keeps its 600 mode; the server's API (65532) must own it.
docker run --rm -v "$REPO/deploy/certs:/certs:ro" alpine tar -C / -cf - certs \
  | remote "rm -rf $DIR/certs && tar -C $DIR -xf - --no-same-owner && chown -R 65532 $DIR/certs"
say "✓ 已同步 certs"
remote "mkdir -p $DIR/images && chown 65532 $DIR/images"
if remote "grep -q '\"$REGISTRY\"' ~/.docker/config.json 2>/dev/null"; then
  say "服务器已登录 $REGISTRY。"
else
  say "服务器要能从 $REGISTRY 拉镜像。"
  ask REGISTRY_USER "用户名："
  ask_secret REGISTRY_PASSWORD "密码（或访问令牌）："
  printf '%s' "$REGISTRY_PASSWORD" | remote "docker login $REGISTRY -u '$REGISTRY_USER' --password-stdin"
fi

stage "拉取 $VERSION 并重启"
confirm "在 $HOST 上切换到 $VERSION 并重启 api？" || { warn "已取消"; exit 1; }
# API_TAG in the server's .env, so a later restart or reboot keeps this version.
remote "cd $DIR && { grep -v '^API_TAG=' .env; echo API_TAG=$VERSION; } > .env.tmp && mv .env.tmp .env && chmod 600 .env \
  && docker compose pull api && docker compose up -d db api"
say "等待 /v1/health …"
for _ in $(seq 20); do
  if health=$(remote "curl -fsS localhost:8080/v1/health" 2>/dev/null); then say "✓ $health"; break; fi
  sleep 3
done
[[ -n "${health:-}" ]] || { warn "30 秒内没通过健康检查：ssh $HOST 'cd $DIR && docker compose logs api --tail 50'"; exit 1; }

finish
note "已部署 $IMAGE:$VERSION 到 $HOST:$DIR"
note "回滚：scripts/deploy.sh 会重新构建；只切回旧版本就在服务器上改 $DIR/.env 的 API_TAG，再 docker compose up -d api"
